---
- hosts: all
  become: true
  tasks:
    - name: install dependecies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - lsb-release
          - software-properties-common
        state: latest
        update_cache: true