---
- hosts: all
  become: true
  tasks:
    - name: install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Check if Docker is installed
      shell: docker --version
      register: result