---
- hosts: all
  become: true
  tasks:
    - name: install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: check if docker is installed
      ansible.builtin.shell: dpkg -l | grep -E 'docker-ce|docker-ce-cli|containerd.io|docker-compose-plugin'
      register: docker
      failed_when: docker.stderr != ''
      changed_when: false