- hosts: all
  ignore_unreachable: true
  tasks:
    - name: Install dependencies
    apt: pkg={{ item }} state=present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  - name: Install Docker
    apt: pkg=docker-ce state=present
